In [1]:
from scipy.stats import randint, uniform

In [2]:
ri = randint(0,10) # 0~9 무작위 수
ri.rvs(11) # 0~9사이 숫자 중 무작위 수 11개 생성

array([8, 4, 1, 3, 9, 1, 1, 1, 7, 1, 7])

In [3]:
import numpy as np

np.unique(ri.rvs(1000), return_counts=True) # 중복된 총 개수를 함께 반환

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([ 99,  98,  97, 106,  98,  97, 103,  97, 107,  98]))

In [4]:
ui = uniform(0,1) # 0~1 사이의 무작위 실수
ui.rvs(5) # 0~1 사이 무작위 실수를 5개 생성

array([0.3413809 , 0.5579921 , 0.8073252 , 0.59970841, 0.1066027 ])